spring:
  application:
    name: msclientes

server:
  port: 0 #sobe a app numa porta aleatoria

eureka:
  client:
    service-url: #estamos setando onde iremos nos registrar - servidor eureka (config de client)
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
