spring:
  application:
    name: mscartoes
  rabbitmq: #broker
    host: localhost
    port: 5672
    username: guest
    password: guest


server:
  port: 0

eureka:
  client:
    service-url: #estamos setando onde iremos nos registrar - servidor eureka (config de client)
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} #registra os ms com nomes diferentes

#filas do nosso rabbitmq
mq:
  queues:
    emissao-cartoes: emissao-cartoes